services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./flask_server:/flask_server
      - ./Image-Comparator-Data:/Image-Comparator-Data 
    working_dir: /flask_server
    environment:
      - FLASK_APP=${FLASK_APP}
      - IMAGE_COMPARATOR_DATA=${IMAGE_COMPARATOR_DATA}
      - DNS=${DNS}
      - SSL=${SSL}
      - DB_PORT=${DB_PORT}
      - HTTP_PORT=${HTTP_PORT}
      - DEPLOY=${DEPLOY}
      - COUCH_DB=${COUCH_DB}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - ADMIN_PARTY=${ADMIN_PARTY}
      - SECRET_KEY=${SECRET_KEY}
    command: bash -c "/flask_server/OPTIMEyes/utils/setup.sh"
    # command: sleep 1000000
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:latest
    ports:
      - "${COUCH_PORT}:5984"
    environment:
      - COUCH_DB=${COUCH_DB}
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - DB_LOCATION=${DB_LOCATION}
      - COUCH_PORT=${COUCH_PORT}
    volumes:
      - ${DB_LOCATION}:/opt/couchdb/data
      - ./flask_server:/flask_server

  monailabel:
    build:
      context: ./monailabel
    ports:
      - 8000:8000
    volumes:
      - ./monailabel:/monailabel
    environment:
      - MONAI_LABEL_ENV=development
    command: sleep 100000