site_name: OPTIMEyes
nav:
  - Instructions for Setup: index.md
  - Use: use.md
  - Interactive Shell for Flask: interactive_shell_for_flask.md
  - Load Data: load_data.md
  - Purge Data: purge_data.md
  - SSL: ssl.md
  - MonaiLabel: monailabel.md
  - MKdocs: mkdocs.md
theme:
  name: readthedocs